(define (square x) (* x x))
(define (sum-of-square a b)
  (+ (square a)
     (square b)))
(define (bigger a b)
  (cond ((> a b) a)
        (else b)))
(define (sum-square-of-two-lager a b c)
  (sum-of-square (bigger a b) (bigger b c)))
(sum-square-of-two-lager 5 2 0)